# Generated by Django 3.2.8 on 2021-10-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sliderimage', models.ImageField(upload_to='images/')),
                ('headline', models.CharField(max_length=200)),
                ('subtext', models.TextField(max_length=400)),
            ],
        ),
    ]
