# Generated by Django 3.2.8 on 2021-10-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_mainslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jobtitle',
            field=models.CharField(default='Title', max_length=200),
        ),
    ]
